import { LeadsEntity } from './leads.entity';

export const leadsLocalDb: LeadsEntity[] = [
  {
    id: 1,
    nationalId: '123456789',
    firstName: 'Juan',
    lastName: 'Pérez',
    birthDate: '1990-01-15',
    email: 'juan.perez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 2,
    nationalId: '987654321',
    firstName: 'María',
    lastName: 'González',
    birthDate: '1985-05-23',
    email: 'maria.gonzalez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 3,
    nationalId: '112233445',
    firstName: 'Carlos',
    lastName: 'Sánchez',
    birthDate: '1992-03-11',
    email: 'carlos.sanchez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 4,
    nationalId: '223344556',
    firstName: 'Ana',
    lastName: 'Martínez',
    birthDate: '1988-07-22',
    email: 'ana.martinez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 5,
    nationalId: '334455667',
    firstName: 'Luis',
    lastName: 'Fernández',
    birthDate: '1980-05-10',
    email: 'luis.fernandez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 6,
    nationalId: '445566778',
    firstName: 'Laura',
    lastName: 'García',
    birthDate: '1995-11-30',
    email: 'laura.garcia@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 7,
    nationalId: '556677889',
    firstName: 'Miguel',
    lastName: 'Rodríguez',
    birthDate: '1991-04-18',
    email: 'miguel.rodriguez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 8,
    nationalId: '667788990',
    firstName: 'Sofía',
    lastName: 'López',
    birthDate: '1987-09-14',
    email: 'sofia.lopez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 9,
    nationalId: '778899001',
    firstName: 'Andrés',
    lastName: 'Gómez',
    birthDate: '1993-06-21',
    email: 'andres.gomez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 10,
    nationalId: '889900112',
    firstName: 'Patricia',
    lastName: 'Díaz',
    birthDate: '1990-02-25',
    email: 'patricia.diaz@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 11,
    nationalId: '990011223',
    firstName: 'Jorge',
    lastName: 'Vargas',
    birthDate: '1982-12-01',
    email: 'jorge.vargas@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 12,
    nationalId: '101122334',
    firstName: 'Valeria',
    lastName: 'Morales',
    birthDate: '1994-08-07',
    email: 'valeria.morales@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 13,
    nationalId: '111233445',
    firstName: 'Raúl',
    lastName: 'Ríos',
    birthDate: '1989-10-30',
    email: 'raul.rios@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 14,
    nationalId: '122344556',
    firstName: 'Carmen',
    lastName: 'Romero',
    birthDate: '1984-05-15',
    email: 'carmen.romero@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 15,
    nationalId: '133455667',
    firstName: 'Gabriel',
    lastName: 'Torres',
    birthDate: '1996-07-29',
    email: 'gabriel.torres@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 16,
    nationalId: '144566778',
    firstName: 'Daniela',
    lastName: 'Ramírez',
    birthDate: '1992-11-11',
    email: 'daniela.ramirez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 17,
    nationalId: '155677889',
    firstName: 'José',
    lastName: 'Mendoza',
    birthDate: '1990-09-03',
    email: 'jose.mendoza@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 18,
    nationalId: '166788990',
    firstName: 'Elena',
    lastName: 'Flores',
    birthDate: '1987-02-20',
    email: 'elena.flores@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 19,
    nationalId: '177899001',
    firstName: 'Pedro',
    lastName: 'Cruz',
    birthDate: '1983-04-25',
    email: 'pedro.cruz@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 20,
    nationalId: '188900112',
    firstName: 'Lucía',
    lastName: 'Reyes',
    birthDate: '1991-01-19',
    email: 'lucia.reyes@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 21,
    nationalId: '199011223',
    firstName: 'Alberto',
    lastName: 'Silva',
    birthDate: '1988-08-05',
    email: 'alberto.silva@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 22,
    nationalId: '200122334',
    firstName: 'Marta',
    lastName: 'Giménez',
    birthDate: '1993-11-09',
    email: 'marta.gimenez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 23,
    nationalId: '211233445',
    firstName: 'Santiago',
    lastName: 'Navarro',
    birthDate: '1995-06-28',
    email: 'santiago.navarro@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 24,
    nationalId: '222344556',
    firstName: 'Claudia',
    lastName: 'Ortega',
    birthDate: '1986-03-13',
    email: 'claudia.ortega@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 25,
    nationalId: '233455667',
    firstName: 'Manuel',
    lastName: 'Espinoza',
    birthDate: '1990-10-02',
    email: 'manuel.espinoza@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 26,
    nationalId: '244566778',
    firstName: 'Alejandra',
    lastName: 'Vega',
    birthDate: '1994-07-16',
    email: 'alejandra.vega@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 27,
    nationalId: '255677889',
    firstName: 'Javier',
    lastName: 'Castro',
    birthDate: '1985-01-12',
    email: 'javier.castro@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 28,
    nationalId: '266788990',
    firstName: 'Paula',
    lastName: 'Blanco',
    birthDate: '1993-09-21',
    email: 'paula.blanco@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 29,
    nationalId: '277899001',
    firstName: 'Rubén',
    lastName: 'Moreno',
    birthDate: '1989-12-14',
    email: 'ruben.moreno@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 30,
    nationalId: '288900112',
    firstName: 'Sara',
    lastName: 'Ruiz',
    birthDate: '1987-04-03',
    email: 'sara.ruiz@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 31,
    nationalId: '299011223',
    firstName: 'Oscar',
    lastName: 'Molina',
    birthDate: '1984-02-27',
    email: 'oscar.molina@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 32,
    nationalId: '300122334',
    firstName: 'Natalia',
    lastName: 'Cano',
    birthDate: '1991-11-07',
    email: 'natalia.cano@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 33,
    nationalId: '311233445',
    firstName: 'Diego',
    lastName: 'Luna',
    birthDate: '1996-08-19',
    email: 'diego.luna@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 34,
    nationalId: '322344556',
    firstName: 'Laura',
    lastName: 'Campos',
    birthDate: '1992-05-26',
    email: 'laura.campos@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 35,
    nationalId: '333455667',
    firstName: 'Francisco',
    lastName: 'Ibáñez',
    birthDate: '1981-03-09',
    email: 'francisco.ibanez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 36,
    nationalId: '344566778',
    firstName: 'Beatriz',
    lastName: 'Ortiz',
    birthDate: '1988-12-22',
    email: 'beatriz.ortiz@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 37,
    nationalId: '355677889',
    firstName: 'Héctor',
    lastName: 'Soto',
    birthDate: '1985-10-06',
    email: 'hector.soto@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 38,
    nationalId: '366788990',
    firstName: 'Mónica',
    lastName: 'Aguilar',
    birthDate: '1990-06-17',
    email: 'monica.aguilar@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 39,
    nationalId: '377899001',
    firstName: 'Gonzalo',
    lastName: 'Delgado',
    birthDate: '1993-02-02',
    email: 'gonzalo.delgado@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 40,
    nationalId: '388900112',
    firstName: 'Victoria',
    lastName: 'Fuentes',
    birthDate: '1984-11-13',
    email: 'victoria.fuentes@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 41,
    nationalId: '399011223',
    firstName: 'Luis',
    lastName: 'Paredes',
    birthDate: '1995-03-04',
    email: 'luis.paredes@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 42,
    nationalId: '400122334',
    firstName: 'Teresa',
    lastName: 'Carrillo',
    birthDate: '1987-05-20',
    email: 'teresa.carrillo@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 43,
    nationalId: '411233445',
    firstName: 'Felipe',
    lastName: 'Galindo',
    birthDate: '1986-02-14',
    email: 'felipe.galindo@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 44,
    nationalId: '422344556',
    firstName: 'Cecilia',
    lastName: 'Herrera',
    birthDate: '1991-06-12',
    email: 'cecilia.herrera@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 45,
    nationalId: '433455667',
    firstName: 'Alonso',
    lastName: 'Lozano',
    birthDate: '1993-12-05',
    email: 'alonso.lozano@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 46,
    nationalId: '444566778',
    firstName: 'Isabel',
    lastName: 'Pérez',
    birthDate: '1982-09-16',
    email: 'isabel.perez@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 47,
    nationalId: '455677889',
    firstName: 'Antonio',
    lastName: 'Ramos',
    birthDate: '1988-01-28',
    email: 'antonio.ramos@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 48,
    nationalId: '466788990',
    firstName: 'Adriana',
    lastName: 'Serrano',
    birthDate: '1990-03-31',
    email: 'adriana.serrano@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 49,
    nationalId: '477899001',
    firstName: 'Ignacio',
    lastName: 'Valencia',
    birthDate: '1987-07-14',
    email: 'ignacio.valencia@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
  {
    id: 50,
    nationalId: '488900112',
    firstName: 'Julia',
    lastName: 'Zapata',
    birthDate: '1992-08-25',
    email: 'julia.zapata@example.com',
    status: 'pending',
    validationResults: {
      nationalRegistryCheck: null,
      judicialRecordsCheck: null,
      prospectQualificationScore: null,
    },
  },
];
